### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by ghost** [alketola/harbour-ostos#9]
Add french translation.

	<?xml version="1.0" encoding="utf-8"?>
	<!DOCTYPE TS>
	<TS version="2.1" language="fr">
	<context>
		<name>CoverPage</name>
		<message>
			<source>Ostos</source>
			<translation>Panier</translation>
		</message>
	</context>
	<context>
		<name>FilterPage</name>
		<message>
			<source>Accept</source>
			<translation>Accepter</translation>
		</message>
		<message>
			<source>No shops</source>
			<translation>Aucun magasin</translation>
		</message>
		<message>
			<source>Add new shop</source>
			<translation>Ajouter un nouveau magasin</translation>
		</message>
		<message>
			<source>Undo edits</source>
			<translation>Annuler les modifications</translation>
		</message>
	</context>
	<context>
		<name>FirstPage</name>
		<message>
			<source>-</source>
			<translation>-</translation>
		</message>
		<message>
			<source>Help</source>
			<translation>Aide</translation>
		</message>
		<message>
			<source>Settings</source>
			<translation>Paramètres</translation>
		</message>
		<message>
			<source>Edit shops</source>
			<translation>Modifier les magasins</translation>
		</message>
		<message>
			<source>Hide bought</source>
			<translation>Masquer les articles achetés</translation>
		</message>
		<message>
			<source>Search to buy</source>
			<translation>Rechercher des articles à acheter</translation>
		</message>
		<message>
			<source>Clearing</source>
			<translation>Nettoyer</translation>
		</message>
	</context>
	<context>
		<name>ItemAddPage</name>
		<message>
			<source>Search</source>
			<translation>Rechercher</translation>
		</message>
	</context>
	<context>
		<name>ItemEditPage</name>
		<message>
			<source>Accept</source>
			<translation>Accepter</translation>
		</message>
		<message>
			<source>Item Name</source>
			<translation>Libellé de l'article</translation>
		</message>
		<message>
			<source>Quantity</source>
			<translation>Quantité</translation>
		</message>
		<message>
			<source>Unit</source>
			<translation>Unité</translation>
		</message>
		<message>
			<source>Item Class</source>
			<translation>Catégorie</translation>
		</message>
		<message>
			<source>Shop</source>
			<translation>Magasin</translation>
		</message>
		<message>
			<source>Edit shops</source>
			<translation>Editer les magasins</translation>
		</message>
	</context>
	<context>
		<name>LineButtonsMenu</name>
		<message>
			<source>Hiding Item</source>
			<translation>Masquer l'article</translation>
		</message>
		<message>
			<source>Deleting Item</source>
			<translation>Supprimer l'article</translation>
		</message>
	</context>
	<context>
		<name>NewShopDialog</name>
		<message>
			<source>Add new shop</source>
			<translation>Ajouter un nouveau magasin</translation>
		</message>
		<message>
			<source>Shop name</source>
			<translation>Nom du magasin</translation>
		</message>
	</context>
	<context>
		<name>OldHelpTxt</name>
		<message>
			<source>Help</source>
			<translation>Aide</translation>
		</message>
		<message>
			<source>Add new items by swithcing to search page on the right (on first item in the pulldown menu.
	</source>
			<translation>Ajouter des nouveaux articles en se déplaçant sur la page de recherche à droite (premier élément du menu déroulant.</translation>
		</message>
		<message>
			<source>The items have states, indicated by the icon on the left of each shopping list item.
	</source>
			<translation>Les produits ont des status, indiqués par l'icône sur la gauche de chaque article de la liste de courses.</translation>
		</message>
		<message>
			<source>The state can be toggled like by clicking the state icon on the left.
	</source>
			<translation>Le statut peut être modifié en cliquant sur l'icone à gauche.</translation>
		</message>
		<message>
			<source>The context menu has options to hide, edit, flag</source>
			<translation>Le menu contextuel a des options pour masquer, éditer et marquer</translation>
		</message>
		<message>
			<source>Add new items by swithcing to search page on the right on first item in the pulldown menu</source>
			<translation>Ajouter des nouveaux articles en se déplaçant sur la page de recherche à droite sur le premier élément du menu déroulant</translation>
		</message>
		<message>
			<source>The item is listed as to buy</source>
			<translation>L'article est listé dans la liste de courses</translation>
		</message>
		<message>
			<source>The item has been bought</source>
			<translation>L'article a été acheté</translation>
		</message>
		<message>
			<source>The item is listed as flagged (e.g. find later)</source>
			<translation>L'article est marqué</translation>
		</message>
		<message>
			<source> increase quantity, decrease quantity and delete the item.
	</source>
			<translation> augmenter la quantité, diminuer la quantité et supprimer le produit</translation>
		</message>
	</context>
	<context>
		<name>SettingsPage</name>
		<message>
			<source>Settings</source>
			<translation>Paramètres</translation>
		</message>
		<message>
			<source>List refresh interval</source>
			<translation>Intervalle de rafraichissement de la liste</translation>
		</message>
		<message>
			<source>DELETE DATABASE TABLES</source>
			<translation>SUPPRIMER LA BASE DE DONNEES</translation>
		</message>
		<message>
			<source>DELETING ALL DATA</source>
			<translation>SUPPRIMER TOUTES LES DONNEES</translation>
		</message>
		<message>
			<source>Enable WWW help</source>
			<translation>Activer l'aide sur internet</translation>
		</message>
		<message>
			<source>Enable Help file read from Web and use of Google translator for unknown languages</source>
			<translation>Activer l'aide sur internet et utiliser la traduction Google pour les langues inconnues</translation>
		</message>
		<message>
			<source>Enable Class Section Headings in the Shoppinglist</source>
			<translation>Activer le regroupement par catégorie dans la liste de courses</translation>
		</message>
		<message>
			<source>Order shopping list also by class</source>
			<translation>Trier également la liste de courses par catégorie</translation>
		</message>
	</context>
	<context>
		<name>ShopPage</name>
		<message>
			<source>Accept</source>
			<translation>Accepter</translation>
		</message>
		<message>
			<source>Back</source>
			<translation>Retour</translation>
		</message>
		<message>
			<source>No items</source>
			<translation>Aucun produit</translation>
		</message>
		<message>
			<source>Add new shop</source>
			<translation>Ajouter un nouveau magasin</translation>
		</message>
		<message>
			<source>Edit</source>
			<translation>Editer</translation>
		</message>
		<message>
			<source>Delete</source>
			<translation>Supprimer</translation>
		</message>
	</context>
	<context>
		<name>Splash</name>
		<message>
			<source>Shopping list</source>
			<translation>Liste de courses</translation>
		</message>
		<message>
			<source>Continue</source>
			<translation>Continuer</translation>
		</message>
		<message>
			<source>Ostos</source>
			<translation>Liste de courses</translation>
		</message>
	</context>
	<context>
		<name>harbour-ostos</name>
		<message>
			<source>Updating</source>
			<translation>Mise à jour</translation>
		</message>
		<message>
			<source></source>
			<translatorcomment>Notificacion sobre actualización, (se puede perder resposividad por un momento)</translatorcomment>
			<translation></translation>
		</message>
	</context>
	</TS>

**Comment by alketola** [comment]
Merci beaucoup de traduction française!

Je n'osia faire le traduccion a français pas, ils sont deja plus de vingt
ans de mes etudies.

Voilá, c'est publié toute de suite a GitHub et aussi a Jolla magasin.

2017-01-22 21:40 GMT+01:00 nIQnutn <notifications@github.com>:

**Comment by alketola** [comment]
French transation added to v1.09-0. Voicí le traction francais en version 1.09-0.

**Comment by ghost** [comment]
Merci
